app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.4
  # persist the database between containers by storing it in a volume
  volumes:
    - demo-postgres:/var/lib/postgresql/data

  ports:
    - "5432"
