# New file for Heroku deploy:
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres

################################################################################
# Previous contents:
#app:
#  build: .
#  command: rails server -p 3000 -b '0.0.0.0'
#  volumes:
#    - .:/app
#  ports:
#    - "3000:3000"
#  links:
#    - postgres
#postgres:
#  image: postgres:9.4
#  # persist the database between containers by storing it in a volume
#  volumes:
#    - demo-postgres:/var/lib/postgresql/data
#
#  ports:
#    - "5432"
